# Generated by Django 3.1.12 on 2021-06-15 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('confidence', models.FloatField()),
                ('true_count', models.IntegerField()),
                ('false_count', models.IntegerField()),
                ('pre_classified', models.BooleanField()),
                ('iid', models.ForeignKey(db_column='iid', on_delete=django.db.models.deletion.DO_NOTHING, to='images.image')),
                ('lid', models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.DO_NOTHING, to='labels.label')),
            ],
            options={
                'db_table': 'classification',
            },
        ),
    ]
