# Generated by Django 3.1.12 on 2021-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('trust', models.FloatField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
